version: 2.1
orbs:
  node: circleci/node@5.0.2
  eb: circleci/aws-elastic-beanstalk@2.0.1
  aws-cli: circleci/aws-cli@3.1.1
  aws-elastic-beanstalk: circleci/aws-elastic-beanstalk@2.0.1
jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      - eb/setup
      - aws-cli/setup
      - run:
          name: Install Front-End
          command: |
            npm run frontend:install
      - run:
          name: Install Back-End
          command: |
            npm run backend:install
      - run:
          name: Front-End Lint
          command: |
            echo "TODO: Lint the frontend"
      - run:
          name: Front-End Build
          command: |
            npm run frontend:build
      - run:
          name: Back-End Build
          command: |
            npm run backend:build
      - run:
          name: Deploy Front-End
          command: |
            npm run frontend:deploy
      - run:
          name: Deploy Back-End
          command: |
            npm run backend:deploy

workflows:
  version: 2.1
  build:
    jobs:
      - build:
          filters:
            branches:
              only: main
